### ISSUE TITLE
Permission Problems

### ISSUE THREAD

**Issue by RobRover** [openafg/laravel-docker#1]
Hello. Thanks for your contribution. I experienced the following problems:

I had to do ``` sudo chmod 777 ./* ``` in order to get full permissions when storing images in the public folder.

Even tough I can run ```docker-compose exec app npm install ``` successfully, I can 't run ``` docker-compose exec app npm run watch ```. I'm getting the following error: 
```
> watch
> mix watch

/usr/bin/env: 'node': Permission denied
npm ERR! code 126
npm ERR! path /var/www
npm ERR! command failed
npm ERR! command sh -c mix watch

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-11T09_52_03_927Z-debug.log
```

I would appreciate a solution. Thanks :)

**Comment by afgprogrammer** [comment]
@RobRover you don't need to run `npm run watch`, if you look at the `docker-compose.yaml` file you can find an npm container that is responsible for our watch.
